<?php
/**
 * Form Terms - Form fields, validation, steps, labels
 */
return [
'step1_short' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'step2_short' => [
    'fi' => 'Paikka ja aika',
    'sv' => 'Plats och tid',
    'en' => 'Location and time',
    'it' => 'Luogo e ora',
    'el' => 'Τοποθεσία και χρόνος',
],
'step3_short' => [
    'fi' => 'Sisältö',
    'sv' => 'Innehåll',
    'en' => 'Content',
    'it' => 'Contenuto',
    'el' => 'Περιεχόμενο',
],
'step4_short' => [
    'fi' => 'Kuvat',
    'sv' => 'Bilder',
    'en' => 'Images',
    'it' => 'Immagini',
    'el' => 'Εικόνες',
],
'step5_short' => [
    'fi' => 'Asettelu',
    'sv' => 'Layout',
    'en' => 'Layout',
    'it' => 'Layout',
    'el' => 'Διάταξη',
],
'step6_short' => [
    'fi' => 'Lähetä',
    'sv' => 'Skicka',
    'en' => 'Submit',
    'it' => 'Invia',
    'el' => 'Υποβολή',
],
'form_progress_label' => [
    'fi' => 'Lomakkeen edistyminen',
    'sv' => 'Formulärets framsteg',
    'en' => 'Form progress',
    'it' => 'Avanzamento del modulo',
    'el' => 'Πρόοδος φόρμας',
],
'step1_heading' => [
    'fi' => '1. Valitse tiedotteen tyyppi',
    'sv' => '1. Välj meddelandetyp',
    'en' => '1. Choose flash type',
    'it' => '1. Scegli il tipo di comunicazione',
    'el' => '1. Επιλέξτε τύπο ανακοίνωσης',
],
'step2_heading' => [
    'fi' => '2. Paikka ja aika',
    'sv' => '2. Plats och tid',
    'en' => '2. Location and time',
    'it' => '2. Luogo e ora',
    'el' => '2. Τοποθεσία και χρόνος',
],
'step3_heading' => [
    'fi' => '3. Sisältö',
    'sv' => '3. Innehåll',
    'en' => '3. Content',
    'it' => '3. Contenuto',
    'el' => '3. Περιεχόμενο',
],
'step4_heading' => [
    'fi' => '4. Kuvat',
    'sv' => '4. Bilder',
    'en' => '4. Images',
    'it' => '4. Immagini',
    'el' => '4. Εικόνες',
],
'step5_heading' => [
    'fi' => 'Vaihe 5: Asettelu',
    'sv' => 'Steg 5: Layout',
    'en' => 'Step 5: Layout',
    'it' => 'Fase 5: Layout',
    'el' => 'Βήμα 5: Διάταξη',
],
'step6_heading' => [
    'fi' => 'Vaihe 6: Esikatselu ja lähetys',
    'sv' => 'Steg 6: Förhandsgranskning och skicka',
    'en' => 'Step 6: Preview and submit',
    'it' => 'Fase 6: Anteprima e invio',
    'el' => 'Βήμα 6: Προεπισκόπηση και υποβολή',
],
'step2_help' => [
    'fi' => 'Valitse työmaa, tarkempi sijainti ja tapahtuma-aika.  Tarvittaessa lisätietoja voi tarkentaa seuraavissa vaiheissa.',
    'sv' => 'Välj arbetsplats, närmare plats och tidpunkt. Vid behov kan du lägga till mer information i följande steg.',
    'en' => 'Select worksite, specific location and time. Additional details can be added in the following steps if needed.',
    'it' => 'Seleziona cantiere, posizione specifica e orario. Ulteriori dettagli possono essere aggiunti nei passaggi successivi se necessario.',
    'el' => 'Επιλέξτε εργοτάξιο, συγκεκριμένη τοποθεσία και ώρα. Επιπλέον λεπτομέρειες μπορούν να προστεθούν στα επόμενα βήματα αν χρειαστεί.',
],
'step4_help' => [
    'fi' => 'Lataa vähintään yksi kuva. Voit säätää kuvien paikkaa ja zoomia seuraavassa vaiheessa.',
    'sv' => 'Ladda upp minst en bild. Du kan justera bildernas position och zoom i nästa steg.',
    'en' => 'Upload at least one image. You can adjust the position and zoom in the next step.',
    'it' => 'Carica almeno un\'immagine. Puoi regolare posizione e zoom nel passaggio successivo.',
    'el' => 'Ανεβάστε τουλάχιστον μία εικόνα. Μπορείτε να ρυθμίσετε τη θέση και το ζουμ στο επόμενο βήμα.',
],
'img_main_label' => [
    'fi' => 'Pääkuva',
    'sv' => 'Huvudbild',
    'en' => 'Main image',
    'it' => 'Immagine principale',
    'el' => 'Κύρια εικόνα',
],
'img_2_label' => [
    'fi' => 'Lisäkuva 1',
    'sv' => 'Extrabild 1',
    'en' => 'Extra image 1',
    'it' => 'Immagine extra 1',
    'el' => 'Επιπλέον εικόνα 1',
],
'img_3_label' => [
    'fi' => 'Lisäkuva 2',
    'sv' => 'Extrabild 2',
    'en' => 'Extra image 2',
    'it' => 'Immagine extra 2',
    'el' => 'Επιπλέον εικόνα 2',
],
'log_comment_label' => [
    'fi' => 'Kommentti',
    'en' => 'Comment',
    'sv' => 'Kommentar',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'log_return_reason_label' => [
    'fi' => 'Palautteen syy',
    'en' => 'Reason for return',
    'sv' => 'Anledning till återkoppling',
    'it' => 'Motivo del reso',
    'el' => 'Λόγος επιστροφής',
],
'log_message_to_comms_label' => [
    'fi' => 'Viesti viestinnälle',
    'en' => 'Message to communications',
    'sv' => 'Meddelande till kommunikation',
    'it' => 'Messaggio alla comunicazione',
    'el' => 'Μήνυμα προς επικοινωνία',
],
'root_causes_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Grundorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],
'actions_label' => [
    'fi' => 'Toimenpiteet',
    'sv' => 'Åtgärder',
    'en' => 'Corrective actions',
    'it' => 'Azioni correttive',
    'el' => 'Διορθωτικές ενέργειες',
],
'root_cause_label' => [
    'fi' => 'Juurisyyt',
    'sv' => 'Rotorsaker',
    'en' => 'Root causes',
    'it' => 'Cause radice',
    'el' => 'Βαθύτερες αιτίες',
],
'site_label' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'when_label' => [
    'fi' => 'Milloin?',
    'sv' => 'När?',
    'en' => 'When?',
    'it' => 'Quando?',
    'el' => 'Πότε;',
],
'filter_search_label' => [
    'fi' => 'Vapaa sanahaku',
    'sv' => 'Fritextsökning',
    'en' => 'Free text search',
    'it' => 'Ricerca libera',
    'el' => 'Αναζήτηση ελεύθερου κειμένου',
],
'date_timespan_header' => [
    'fi' => '📅 Aikaväli',
    'sv' => '📅 Tidsperiod',
    'en' => '📅 Time range',
    'it' => '📅 Intervallo di tempo',
    'el' => '📅 Χρονικό διάστημα',
],
'date_preset_all' => [
    'fi' => 'Kaikki ajat',
    'sv' => 'Alla tider',
    'en' => 'All time',
    'it' => 'Tutto il tempo',
    'el' => 'Όλοι οι χρόνοι',
],
'date_preset_7days' => [
    'fi' => 'Viimeiset 7 päivää',
    'sv' => 'Senaste 7 dagar',
    'en' => 'Last 7 days',
    'it' => 'Ultimi 7 giorni',
    'el' => 'Τελευταίες 7 ημέρες',
],
'date_preset_7days_short' => [
    'fi' => 'Viim. 7 pv',
    'sv' => 'Senaste 7 d',
    'en' => 'Last 7 d',
    'it' => 'Ultimi 7 g',
    'el' => 'Τελ. 7 η',
],
'date_preset_30days' => [
    'fi' => 'Viimeiset 30 päivää',
    'sv' => 'Senaste 30 dagar',
    'en' => 'Last 30 days',
    'it' => 'Ultimi 30 giorni',
    'el' => 'Τελευταίες 30 ημέρες',
],
'date_preset_30days_short' => [
    'fi' => 'Viim. 30 pv',
    'sv' => 'Senaste 30 d',
    'en' => 'Last 30 d',
    'it' => 'Ultimi 30 g',
    'el' => 'Τελ. 30 η',
],
'date_preset_month' => [
    'fi' => 'Tämä kuukausi',
    'sv' => 'Denna månad',
    'en' => 'This month',
    'it' => 'Questo mese',
    'el' => 'Αυτός ο μήνας',
],
'date_preset_month_short' => [
    'fi' => 'Tämä kk',
    'sv' => 'Denna mån',
    'en' => 'This month',
    'it' => 'Questo mese',
    'el' => 'Αυτός μήν',
],
'date_preset_custom' => [
    'fi' => 'Mukautettu aikaväli...',
    'sv' => 'Anpassat intervall...',
    'en' => 'Custom range...',
    'it' => 'Intervallo personalizzato...',
    'el' => 'Προσαρμοσμένο διάστημα...',
],
'date_from' => [
    'fi' => 'Alkaen',
    'sv' => 'Från',
    'en' => 'From',
    'it' => 'Da',
    'el' => 'Από',
],
'date_to' => [
    'fi' => 'Päättyen',
    'sv' => 'Till',
    'en' => 'To',
    'it' => 'A',
    'el' => 'Έως',
],
'date_clear' => [
    'fi' => 'Tyhjennä',
    'sv' => 'Rensa',
    'en' => 'Clear',
    'it' => 'Cancella',
    'el' => 'Καθαρισμός',
],
'date_preset_year' => [
    'fi' => 'Tämä vuosi',
    'sv' => 'Detta år',
    'en' => 'This year',
    'it' => 'Quest\'anno',
    'el' => 'Φέτος',
],
'date_month_header' => [
    'fi' => 'Kuukausi',
    'sv' => 'Månad',
    'en' => 'Month',
    'it' => 'Mese',
    'el' => 'Μήνας',
],
'modal_comment_label' => [
    'fi' => 'Kommentti',
    'sv' => 'Kommentar',
    'en' => 'Comment',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'modal_request_label' => [
    'fi' => 'Palautteen syy',
    'sv' => 'Anledning till återkoppling',
    'en' => 'Reason for feedback',
    'it' => 'Motivo del feedback',
    'el' => 'Λόγος ανατροφοδότησης',
],
'modal_to_comms_label' => [
    'fi' => 'Viesti viestinnälle',
    'sv' => 'Meddelande till kommunikation',
    'en' => 'Message to communications',
    'it' => 'Messaggio alla comunicazione',
    'el' => 'Μήνυμα προς το τμήμα επικοινωνίας',
],
'layout_label' => [
    'fi' => 'Kuvien asettelu',
    'sv' => 'Bildlayout',
    'en' => 'Image layout',
    'it' => 'Disposizione immagini',
    'el' => 'Διάταξη εικόνων',
],
'slider_zoom_label' => [
    'fi' => 'Zoom',
    'sv' => 'Zoom',
    'en' => 'Zoom',
    'it' => 'Zoom',
    'el' => 'Ζουμ',
],
'slider_position_x_label' => [
    'fi' => 'Sijainti X',
    'sv' => 'Position X',
    'en' => 'Position X',
    'it' => 'Posizione X',
    'el' => 'Θέση X',
],
'slider_position_y_label' => [
    'fi' => 'Sijainti Y',
    'sv' => 'Position Y',
    'en' => 'Position Y',
    'it' => 'Posizione Y',
    'el' => 'Θέση Y',
],
'settings_worksites_add_label' => [
    'fi' => 'Uusi työmaa:',
    'sv' => 'Ny arbetsplats:',
    'en' => 'New worksite:',
    'it' => 'Nuovo cantiere:',
    'el' => 'Νέο εργοτάξιο:',
],
'lang_selection_label' => [
    'fi' => 'Safetyflashin kieli / Language of Safetyflash',
    'sv' => 'Safetyflashens språk / Language of Safetyflash',
    'en' => 'Safetyflash language',
    'it' => 'Lingua del Safetyflash',
    'el' => 'Γλώσσα του Safetyflash',
],
'type_selection_label' => [
    'fi' => 'Valitse Safetyflash-tyyppi',
    'sv' => 'Välj Safetyflash-typ',
    'en' => 'Choose Safetyflash type',
    'it' => 'Scegli il tipo di Safetyflash',
    'el' => 'Επιλέξτε τύπο Safetyflash',
],
'site_detail_label' => [
    'fi' => 'Tarkempi sijainti',
    'sv' => 'Närmare plats',
    'en' => 'Specific location',
    'it' => 'Posizione specifica',
    'el' => 'Συγκεκριμένη τοποθεσία',
],
'related_flash_label' => [
    'fi' => 'Mihin tapahtumaan tutkinta liittyy? ',
    'sv' => 'Vilken händelse gäller utredningen?',
    'en' => 'Which incident does this investigation relate to?',
    'it' => 'A quale incidente si riferisce questa indagine?',
    'el' => 'Σε ποιο περιστατικό αναφέρεται αυτή η έρευνα;',
],
'title_internal_label' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'preview_label' => [
    'fi' => 'Esikatselu',
    'en' => 'Preview',
    'sv' => 'Förhandsgranskning',
    'it' => 'Anteprima',
    'el' => 'Προεπισκόπηση',
],
'short_title_label' => [
    'fi' => 'Lyhyt kuvaus',
    'en' => 'Short description',
    'sv' => 'Kort beskrivning',
    'it' => 'Breve descrizione',
    'el' => 'Σύντομη περιγραφή',
],
'description_label' => [
    'fi' => 'Kuvaus',
    'en' => 'Description',
    'sv' => 'Beskrivning',
    'it' => 'Descrizione',
    'el' => 'Περιγραφή',
],
'validation_fill_missing' => [
    'fi' => 'Täytä puuttuvat tiedot:',
    'sv' => 'Fyll i saknad information:',
    'en' => 'Fill in missing information:',
    'it' => 'Compila le informazioni mancanti:',
    'el' => 'Συμπληρώστε τις ελλείπουσες πληροφορίες:',
],
'validation_select_language' => [
    'fi' => 'Valitse kieli',
    'sv' => 'Välj språk',
    'en' => 'Select language',
    'it' => 'Seleziona lingua',
    'el' => 'Επιλέξτε γλώσσα',
],
'validation_select_type' => [
    'fi' => 'Valitse tiedotteen tyyppi',
    'sv' => 'Välj typ av meddelande',
    'en' => 'Select flash type',
    'it' => 'Seleziona tipo di flash',
    'el' => 'Επιλέξτε τύπο flash',
],
'validation_select_worksite' => [
    'fi' => 'Valitse työmaa',
    'sv' => 'Välj arbetsplats',
    'en' => 'Select worksite',
    'it' => 'Seleziona cantiere',
    'el' => 'Επιλέξτε εργοτάξιο',
],
'validation_enter_event_time' => [
    'fi' => 'Syötä tapahtuma-aika',
    'sv' => 'Ange händelsetid',
    'en' => 'Enter event time',
    'it' => 'Inserisci orario evento',
    'el' => 'Εισάγετε ώρα συμβάντος',
],
'validation_time_not_future' => [
    'fi' => 'Tapahtuma-aika ei voi olla tulevaisuudessa',
    'sv' => 'Händelsetiden kan inte vara i framtiden',
    'en' => 'Event time cannot be in the future',
    'it' => 'L\'orario dell\'evento non può essere nel futuro',
    'el' => 'Η ώρα συμβάντος δεν μπορεί να είναι στο μέλλον',
],
'validation_select_base_or_worksite' => [
    'fi' => 'Valitse alkuperäinen tiedote tai syötä työmaa',
    'sv' => 'Välj originalmeddelande eller ange arbetsplats',
    'en' => 'Select base flash or enter worksite',
    'it' => 'Seleziona flash di base o inserisci cantiere',
    'el' => 'Επιλέξτε βασικό flash ή εισάγετε εργοτάξιο',
],
'validation_enter_title' => [
    'fi' => 'Syötä sisäinen otsikko',
    'sv' => 'Ange intern rubrik',
    'en' => 'Enter internal title',
    'it' => 'Inserisci titolo interno',
    'el' => 'Εισάγετε εσωτερικό τίτλο',
],
'validation_enter_short_desc' => [
    'fi' => 'Syötä lyhyt kuvaus',
    'sv' => 'Ange kort beskrivning',
    'en' => 'Enter short description',
    'it' => 'Inserisci breve descrizione',
    'el' => 'Εισάγετε σύντομη περιγραφή',
],
'validation_short_desc_too_long' => [
    'fi' => 'Lyhyt kuvaus on liian pitkä (max 85 merkkiä)',
    'sv' => 'Kort beskrivning är för lång (max 85 tecken)',
    'en' => 'Short description is too long (max 85 characters)',
    'it' => 'La breve descrizione è troppo lunga (max 85 caratteri)',
    'el' => 'Η σύντομη περιγραφή είναι πολύ μεγάλη (μέγ. 85 χαρακτήρες)',
],
'validation_enter_description' => [
    'fi' => 'Syötä tapahtuvan kuvaus',
    'sv' => 'Ange händelsebeskrivning',
    'en' => 'Enter event description',
    'it' => 'Inserisci descrizione evento',
    'el' => 'Εισάγετε περιγραφή συμβάντος',
],
'validation_desc_too_long' => [
    'fi' => 'Kuvaus on liian pitkä (max 950 merkkiä)',
    'sv' => 'Beskrivningen är för lång (max 950 tecken)',
    'en' => 'Description is too long (max 950 characters)',
    'it' => 'La descrizione è troppo lunga (max 950 caratteri)',
    'el' => 'Η περιγραφή είναι πολύ μεγάλη (μέγ. 950 χαρακτήρες)',
],
'validation_root_causes_too_long' => [
    'fi' => 'Juurisyyt-teksti on liian pitkä (max 1500 merkkiä)',
    'sv' => 'Grundorsaker-texten är för lång (max 1500 tecken)',
    'en' => 'Root causes text is too long (max 1500 characters)',
    'it' => 'Il testo delle cause principali è troppo lungo (max 1500 caratteri)',
    'el' => 'Το κείμενο των βασικών αιτιών είναι πολύ μεγάλο (μέγ. 1500 χαρακτήρες)',
],
'validation_actions_too_long' => [
    'fi' => 'Toimenpiteet-teksti on liian pitkä (max 1500 merkkiä)',
    'sv' => 'Åtgärder-texten är för lång (max 1500 tecken)',
    'en' => 'Actions text is too long (max 1500 characters)',
    'it' => 'Il testo delle azioni è troppo lungo (max 1500 caratteri)',
    'el' => 'Το κείμενο των ενεργειών είναι πολύ μεγάλο (μέγ. 1500 χαρακτήρες)',
],
'validation_image_required' => [
    'fi' => 'Lisää vähintään yksi kuva',
    'sv' => 'Lägg till minst en bild',
    'en' => 'Add at least one image',
    'it' => 'Aggiungi almeno un\'immagine',
    'el' => 'Προσθέστε τουλάχιστον μία εικόνα',
],
'card_1_label' => [
    'fi' => 'Kortti 1',
    'sv' => 'Kort 1',
    'en' => 'Card 1',
    'it' => 'Scheda 1',
    'el' => 'Κάρτα 1',
],
'card_2_label' => [
    'fi' => 'Kortti 2',
    'sv' => 'Kort 2',
    'en' => 'Card 2',
    'it' => 'Scheda 2',
    'el' => 'Κάρτα 2',
],
'email_comment_label' => [
    'fi' => 'Kommentti',
    'sv' => 'Kommentar',
    'en' => 'Comment',
    'it' => 'Commento',
    'el' => 'Σχόλιο',
],
'email_welcome_password_label' => [
    'fi' => 'Kirjautumissalasanasi:',
    'sv' => 'Ditt inloggningslösenord:',
    'en' => 'Your login password:',
    'it' => 'La tua password di accesso:',
    'el' => 'Ο κωδικός πρόσβασής σας:',
],
'preview_site_label' => [
    'fi' => 'Työmaa:',
    'sv' => 'Arbetsplats:',
    'en' => 'Worksite:',
    'it' => 'Cantiere:',
    'el' => 'Εργοτάξιο:',
],
'preview_when_label' => [
    'fi' => 'Milloin:',
    'sv' => 'När:',
    'en' => 'When:',
    'it' => 'Quando:',
    'el' => 'Πότε:',
],
'preview_description_label' => [
    'fi' => 'Mitä tapahtui:',
    'sv' => 'Vad hände:',
    'en' => 'What happened:',
    'it' => 'Cosa è successo:',
    'el' => 'Τι συνέβη:',
],
'preview_root_causes_label' => [
    'fi' => 'Juurisyyt:',
    'sv' => 'Rotorsaker:',
    'en' => 'Root causes:',
    'it' => 'Cause radice:',
    'el' => 'Βαθύτερες αιτίες:',
],
'preview_actions_label' => [
    'fi' => 'Toimenpiteet:',
    'sv' => 'Åtgärder:',
    'en' => 'Corrective actions:',
    'it' => 'Azioni correttive:',
    'el' => 'Διορθωτικές ενέργειες:',
],
'validation_fill_required' => [
    'fi' => 'Täytä pakolliset kentät',
    'sv' => 'Fyll i obligatoriska fält',
    'en' => 'Fill in required fields',
    'it' => 'Compila i campi obbligatori',
    'el' => 'Συμπληρώστε τα υποχρεωτικά πεδία',
],
'log_countries_label' => [
    'fi' => 'Maat',
    'sv' => 'Länder',
    'en' => 'Countries',
    'it' => 'Paesi',
    'el' => 'Χώρες',
],
'occurred_at' => [
    'fi' => 'Muokattu',
    'sv' => 'Redigerad',
    'en' => 'Modified',
    'it' => 'Modificato',
    'el' => 'Τροποποιήθηκε',
],
'log_supervisor_message_label' => [
    'fi' => 'Viesti työmaavastaavalta',
    'sv' => 'Meddelande från arbetsledaren',
    'en' => 'Message from Site Manager',
    'it' => 'Messaggio dal responsabile del sito',
    'el' => 'Μήνυμα από υπεύθυνο εργοταξίου',
],
'modal_send_safety_message_label' => [
    'fi' => 'Viesti turvatiimille (valinnainen)',
    'sv' => 'Meddelande till säkerhetsteamet (valfritt)',
    'en' => 'Message to safety team (optional)',
    'it' => 'Messaggio al team di sicurezza (facoltativo)',
    'el' => 'Μήνυμα στην ομάδα ασφαλείας (προαιρετικό)',
],
'validation_email_invalid' => [
    'fi' => 'Anna kelvollinen sähköpostiosoite',
    'en' => 'Enter a valid email address',
    'sv' => 'Ange en giltig e-postadress',
    'it' => 'Inserisci un indirizzo email valido',
    'el' => 'Εισαγάγετε μια έγκυρη διεύθυνση email',
],
'validation_min_length' => [
    'fi' => 'Vähintään {n} merkkiä',
    'en' => 'At least {n} characters',
    'sv' => 'Minst {n} tecken',
    'it' => 'Almeno {n} caratteri',
    'el' => 'Τουλάχιστον {n} χαρακτήρες',
],
'validation_required' => [
    'fi' => 'Pakollinen kenttä',
    'en' => 'Required field',
    'sv' => 'Obligatoriskt fält',
    'it' => 'Campo obbligatorio',
    'el' => 'Υποχρεωτικό πεδίο',
],
'feedback_title_label' => [
    'fi' => 'Otsikko',
    'sv' => 'Titel',
    'en' => 'Title',
    'it' => 'Titolo',
    'el' => 'Τίτλος',
],
'feedback_category_label' => [
    'fi' => 'Kategoria',
    'sv' => 'Kategori',
    'en' => 'Category',
    'it' => 'Categoria',
    'el' => 'Κατηγορία',
],
'feedback_description_label' => [
    'fi' => 'Kuvaus',
    'sv' => 'Beskrivning',
    'en' => 'Description',
    'it' => 'Descrizione',
    'el' => 'Περιγραφή',
],
'feedback_admin_notes_label' => [
    'fi' => 'Admin-muistiinpanot',
    'sv' => 'Admin-anteckningar',
    'en' => 'Admin Notes',
    'it' => 'Note amministratore',
    'el' => 'Σημειώσεις διαχειριστή',
],
'time_just_now' => [
    'fi' => 'Juuri nyt',
    'sv' => 'Just nu',
    'en' => 'Just now',
    'it' => 'Proprio ora',
    'el' => 'Μόλις τώρα',
],
'standalone_investigation_label' => [
    'fi' => 'Luo itsenäinen tutkintatiedote (ilman pohjaa)',
    'sv' => 'Skapa en fristående utredningsrapport (utan grund)',
    'en' => 'Create standalone investigation report (without base)',
    'it' => 'Crea rapporto di indagine indipendente (senza base)',
    'el' => 'Δημιουργία αυτόνομης αναφοράς έρευνας (χωρίς βάση)',
],
'standalone_investigation_help' => [
    'fi' => 'Valitse tämä jos haluat luoda tutkintatiedotteen ilman ensitiedotetta tai vaaratilannetiedotetta pohjana.',
    'sv' => 'Välj detta om du vill skapa en utredningsrapport utan en första rapport eller en farlig situation som grund.',
    'en' => 'Select this if you want to create an investigation report without a first report or danger situation as a base.',
    'it' => 'Seleziona questo se vuoi creare un rapporto di indagine senza una prima relazione o una situazione pericolosa come base.',
    'el' => 'Επιλέξτε αυτό εάν θέλετε να δημιουργήσετε μια αναφορά έρευνας χωρίς μια πρώτη αναφορά ή μια επικίνδυνη κατάσταση ως βάση.',
],
'validation_select_base_or_standalone' => [
    'fi' => 'Valitse pohja tai itsenäinen tutkintatiedote',
    'sv' => 'Välj grund eller fristående utredningsrapport',
    'en' => 'Select base or standalone investigation',
    'it' => 'Seleziona base o indagine indipendente',
    'el' => 'Επιλέξτε βάση ή αυτόνομη έρευνα',
],
// Lisää tämä olemassa olevaan form.php tiedostoon

'select_inspector_title' => [
    'fi' => 'Valitse tarkistaja',
    'sv' => 'Välj granskare',
    'en' => 'Select reviewer',
    'it' => 'Seleziona revisore',
    'el' => 'Επιλέξτε ελεγκτή',
],

'worksite_supervisors_label_prefix' => [
    'fi' => 'Työmaan',
    'sv' => 'Arbetsplatsens',
    'en' => 'Worksite',
    'it' => 'Responsabili del cantiere',
    'el' => 'Υπεύθυνοι εργοταξίου',
],

'worksite_supervisors_label_suffix' => [
    'fi' => 'työmaavastaavat:',
    'sv' => 'ansvariga:',
    'en' => 'sitemanagers:',
    'it' => ':',
    'el' => ':',
],

'search_other_worksites_label' => [
    'fi' => 'Hae muilta työmailta:',
    'sv' => 'Sök från andra arbetsplatser:',
    'en' => 'Search from other worksites:',
    'it' => 'Cerca da altri cantieri:',
    'el' => 'Αναζήτηση από άλλα εργοτάξια:',
],

'search_name_or_worksite_placeholder' => [
    'fi' => 'Hae nimellä tai työmaalla...',
    'sv' => 'Sök med namn eller arbetsplats...',
    'en' => 'Search by name or worksite...',
    'it' => 'Cerca per nome o cantiere...',
    'el' => 'Αναζήτηση με όνομα ή εργοτάξιο...',
],

'selected_label' => [
    'fi' => 'valittu',
    'sv' => 'vald',
    'en' => 'selected',
    'it' => 'selezionato',
    'el' => 'επιλεγμένο',
],

'content_exceeds_single_slide' => [
    'fi' => 'Sisältö ylittää suositellun pituuden. Tiedote jaetaan kahdelle dialle.',
    'sv' => 'Innehållet överskrider rekommenderad längd. Meddelandet delas på två sidor.',
    'en' => 'Content exceeds recommended length. Report will be split into two slides.',
    'it' => 'Il contenuto supera la lunghezza consigliata. Il rapporto sarà diviso in due slide.',
    'el' => 'Το περιεχόμενο υπερβαίνει το συνιστώμενο μήκος. Η αναφορά θα χωριστεί σε δύο διαφάνειες.',
],
'two_slides_notice_title' => [
    'fi' => 'Huomio',
    'sv' => 'Observera',
    'en' => 'Notice',
    'it' => 'Avviso',
    'el' => 'Ειδοποίηση',
],
'two_slides_notice_text' => [
    'fi' => 'Sisältö ylittää suositellun pituuden. Tiedote jaetaan kahdelle dialle.',
    'sv' => 'Innehållet överskrider rekommenderad längd. Meddelandet delas på två sidor.',
    'en' => 'Content exceeds recommended length. Report will be split into two slides.',
    'it' => 'Il contenuto supera la lunghezza consigliata. Il rapporto sarà diviso in due slide.',
    'el' => 'Το περιεχόμενο υπερβαίνει το συνιστώμενο μήκος. Η αναφορά θα χωριστεί σε δύο διαφάνειες.',
],
'submission_comment_label' => [
    'fi' => 'Viesti hyväksyjälle (valinnainen)',
    'sv' => 'Meddelande till granskaren (valfritt)',
    'en' => 'Message to reviewer (optional)',
    'it' => 'Messaggio al revisore (opzionale)',
    'el' => 'Μήνυμα προς τον ελεγκτή (προαιρετικό)',
],
'submission_comment_placeholder' => [
    'fi' => 'Lisää tarvittaessa lisätietoja käsittelijöille (työmaavastaava, turvatiimi ja viestintä)',
    'sv' => 'Lägg vid behov till ytterligare information för handläggare (arbetsplatsansvarig, säkerhetsteam och kommunikation)',
    'en' => 'Add additional information for the handlers if needed (site manager, safetyteam and communications)',
    'it' => 'Aggiungi, se necessario, ulteriori informazioni per i responsabili (responsabile del sito, team di sicurezza e comunicazione)',
    'el' => 'Προσθέστε, εάν χρειάζεται, επιπλέον πληροφορίες για τους υπεύθυνους (υπεύθυνος εργοταξίου, ομάδα ασφάλειας και επικοινωνία)',
],
'submission_comment_help' => [
    'fi' => 'Viesti näkyy hyväksyjälle sähköpostissa ja SafetyFlashin kommenteissa.',
    'sv' => 'Meddelandet visas för granskaren i e-post och i SafetyFlash-kommentarer.',
    'en' => 'The message will be shown to the reviewer in email and SafetyFlash comments.',
    'it' => 'Il messaggio verrà mostrato al revisore nell\'email e nei commenti SafetyFlash.',
    'el' => 'Το μήνυμα θα εμφανιστεί στον ελεγκτή στο email και στα σχόλια SafetyFlash.',
],
'submission_comment_badge' => [
    'fi' => 'Lähetyksen viesti',
    'sv' => 'Inskickningsmeddelande',
    'en' => 'Submission message',
    'it' => 'Messaggio di invio',
    'el' => 'Μήνυμα υποβολής',
],
'font_size_label' => [
    'fi' => 'Tekstin koko',
    'sv' => 'Textstorlek',
    'en' => 'Text size',
    'it' => 'Dimensione testo',
    'el' => 'Μέγεθος κειμένου',
],
'font_size_auto' => [
    'fi' => 'Automaattinen',
    'sv' => 'Automatisk',
    'en' => 'Automatic',
    'it' => 'Automatico',
    'el' => 'Αυτόματο',
],
'editing_this_flash' => [
    'fi' => 'muokkaa tätä tiedotetta',
    'sv' => 'redigerar denna notis',
    'en' => 'is editing this flash',
    'it' => 'sta modificando questo avviso',
    'el' => 'επεξεργάζεται αυτή την ειδοποίηση',
],
'started' => [
    'fi' => 'aloitettu',
    'sv' => 'startade',
    'en' => 'started',
    'it' => 'iniziato',
    'el' => 'ξεκίνησε',
],
'ago' => [
    'fi' => 'sitten',
    'sv' => 'sedan',
    'en' => 'ago',
    'it' => 'fa',
    'el' => 'πριν',
],
'continue_anyway' => [
    'fi' => 'Jatka silti',
    'sv' => 'Fortsätt ändå',
    'en' => 'Continue anyway',
    'it' => 'Continua comunque',
    'el' => 'Συνέχεια ούτως ή άλλως',
],
];